pump_pid_front:
  ros__parameters:
    kp: 0.8
    ki: 0.1
    kd: 0.02
    rate_hz: 50.0
    u_min: 0.0
    u_max: 1.0
    integral_limit: 10.0
    topic_p_d: /soft/front/p_d
    topic_p_act: /soft/front/p_act
    topic_pwm: /soft/front/pump_pwm

pump_pid_rear:
  ros__parameters:
    kp: 0.8
    ki: 0.1
    kd: 0.02
    rate_hz: 50.0
    u_min: 0.0
    u_max: 1.0
    integral_limit: 10.0
    topic_p_d: /soft/rear/p_d
    topic_p_act: /soft/rear/p_act
    topic_pwm: /soft/rear/pump_pwm
