locomotion_task_server:
  ros__parameters:
    out_topic: /joint_goal
    rate_hz: 100.0
    default_require: [J1, J2, J3, J4, J5, J6, J7]
    settle_consecutive: 2
    inter_cycle_wait_s: 0.20   # if omitted, equals after_phase_wait_s
    sleep_step_s: 0.005
    min_dwell_s: 0.05          # (optional) time to let motion begin before checking reached
    phase_timeout_s: 6.0       # base; will be extended dynamically if J1/J2 need more time
    global_timeout_s: 2000.0   # as you used for long tests
    hold_on_wait: true

    j12_pos_cmd_scale: [10.0, 10.0]
         
    joint_limits:
      J1: {min: -10.00, max: 10.00}
      J2: {min: -10.00, max: 10.00}
      J3: {min: -0.05, max: 0.05}
      J4: {min: -21.9911486, max:  21.9911486}
      J5: {min: -21.9911486, max:  21.9911486}
      J6: {min: -1.57079633, max:  1.57079633}
      J7: {min: -1.57079633, max:  1.57079633}

    gaits:

      forward:
        meters_per_cycle: 0.10
        between_phase_wait_s: 0.20
        phases:
          p1:
            joints:
              J1: {mode: hold}
              J2: {mode: hold}
              J3: {mode: hold}
              J4: {mode: move_rel, dpos:  0.90, vmax: 1.2, amax: 3.0}
              J5: {mode: move_rel, dpos:  0.90, vmax: 1.2, amax: 3.0}
              J6: {mode: hold}
              J7: {mode: hold}
            actuators: {solenoids_front: true, pumps_front: true, solenoids_back: true, pumps_back: true}
            require: [J4, J5]
          p2:
            timeout_s: 20.0
            after_wait_s: 3.00
            joints:
              J1: {mode: move_rel, dpos:  0.10, vmax: ~, amax: ~}
              J2: {mode: hold}
              J3: {mode: hold}
              J4: {mode: hold}
              J5: {mode: hold}
              J6: {mode: hold}
              J7: {mode: hold}
            actuators: {solenoids_front: false, pumps_front: false, solenoids_back: true, pumps_back: true}
            require: [J1]
          p3:
            timeout_s: 20.0
            after_wait_s: 3.00
            joints:
              J1: {mode: move_rel, dpos: -0.10, vmax: ~, amax: ~}
              J2: {mode: move_rel, dpos:  0.10, vmax: ~, amax: ~}
              J3: {mode: hold}
              J4: {mode: move_rel, dpos:  -0.90, vmax: 1.2, amax: 3.0}
              J5: {mode: move_rel, dpos:  -0.90, vmax: 1.2, amax: 3.0}
              J6: {mode: hold}
              J7: {mode: hold}
            actuators: {solenoids_front: true, pumps_front: true, solenoids_back: true, pumps_back: true}
            require: [J1, J2, J4, J5]
          p4:
            timeout_s: 20.0
            after_wait_s: 3.00
            joints:
              J1: {mode: hold}
              J2: {mode: move_rel, dpos: -0.10, vmax: ~, amax: ~}
              J3: {mode: hold}
              J4: {mode: move_rel, dpos:  0.30, vmax: 1.2, amax: 3.0}
              J5: {mode: move_rel, dpos:  0.30, vmax: 1.2, amax: 3.0}
              J6: {mode: hold}
              J7: {mode: hold}
            actuators: {solenoids_front: true, pumps_front: true, solenoids_back: false, pumps_back: false}
            require: [J2, J4, J5]

      backward:
        meters_per_cycle: 0.10
        between_phase_wait_s: 0.20
        phases:
          p1:
            joints:
              J1: {mode: hold}
              J2: {mode: hold}
              J3: {mode: hold}
              J4: {mode: move_rel, dpos:  0.90, vmax: 1.2, amax: 3.0}
              J5: {mode: move_rel, dpos:  0.90, vmax: 1.2, amax: 3.0}
              J6: {mode: hold}
              J7: {mode: hold}
            actuators: {solenoids_front: true, pumps_front: true, solenoids_back: true, pumps_back: true}
            require: [J4, J5]
          p2:
            joints:
              J1: {mode: hold}
              J2: {mode: move_rel, dpos:  0.10, vmax: 0.15, amax: 2.0}
              J3: {mode: hold}
              J4: {mode: hold}
              J5: {mode: hold}
              J6: {mode: hold}
              J7: {mode: hold}
            actuators: {solenoids_front: true, pumps_front: true, solenoids_back: false, pumps_back: false}
            require: [J2]
          p3:
            joints:
              J1: {mode: move_rel, dpos:  0.10, vmax: 0.15, amax: 2.0}
              J2: {mode: move_rel, dpos: -0.10, vmax: 0.15, amax: 2.0}
              J3: {mode: hold}
              J4: {mode: move_rel, dpos: -0.90, vmax: 1.2, amax: 3.0}
              J5: {mode: move_rel, dpos: -0.90, vmax: 1.2, amax: 3.0}
              J6: {mode: hold}
              J7: {mode: hold}
            actuators: {solenoids_front: true, pumps_front: true, solenoids_back: true, pumps_back: true}
            require: [J1, J2, J4, J5]
          p4:
            joints:
              J1: {mode: move_rel, dpos: -0.10, vmax: 0.15, amax: 2.0}
              J2: {mode: hold}
              J3: {mode: hold}
              J4: {mode: move_rel, dpos:  0.90, vmax: 1.2, amax: 3.0}
              J5: {mode: move_rel, dpos:  0.90, vmax: 1.2, amax: 3.0}
              J6: {mode: hold}
              J7: {mode: hold}
            actuators: {solenoids_front: false, pumps_front: false, solenoids_back: true, pumps_back: true}
            require: [J1, J4, J5]

      right:
        meters_per_cycle: 0.05
        between_phase_wait_s: 0.20
        phases:
          p1:
            joints:
              J1: {mode: hold}
              J2: {mode: hold}
              J3: {mode: hold}
              J4: {mode: move_rel, dpos:  0.30, vmax: 1.2, amax: 3.0}
              J5: {mode: move_rel, dpos:  0.30, vmax: 1.2, amax: 3.0}
              J6: {mode: hold}
              J7: {mode: hold}
            actuators: {solenoids_front: true, pumps_front: true, solenoids_back: true, pumps_back: true}
            require: [J4, J5]

          p2:
            joints:
              J1: {mode: hold}
              J2: {mode: hold}
              J3: {mode: hold}
              J4: {mode: move_rel, dpos: -0.30, vmax: 1.2, amax: 3.0}
              J5: {mode: move_rel, dpos: -0.30, vmax: 1.2, amax: 3.0}
              J6: {mode: hold}
              J7: {mode: hold}
            actuators: {solenoids_front: true, pumps_front: true, solenoids_back: true, pumps_back: true}
            require: [J4, J5]

          p3:
            joints:
              J1: {mode: hold}
              J2: {mode: hold}
              J3: {mode: move_abs, pos:  0.05, vmax: 0.05, amax: 0.20}
              J4: {mode: hold}
              J5: {mode: hold}
              J6: {mode: hold}
              J7: {mode: hold}
            actuators: {solenoids_front: true, pumps_front: true, solenoids_back: true, pumps_back: true}
            require: [J3]

          p4:
            joints:
              J1: {mode: hold}
              J2: {mode: hold}
              J3: {mode: hold}
              J4: {mode: move_rel, dpos:  0.30, vmax: 1.2, amax: 3.0}
              J5: {mode: move_rel, dpos:  0.30, vmax: 1.2, amax: 3.0}
              J6: {mode: hold}
              J7: {mode: hold}
            actuators: {solenoids_front: true, pumps_front: true, solenoids_back: true, pumps_back: true}
            require: [J4, J5]

          p5:
            joints:
              J1: {mode: hold}
              J2: {mode: hold}
              J3: {mode: hold}
              J4: {mode: hold}
              J5: {mode: hold}
              J6: {mode: hold}
              J7: {mode: hold}
            actuators: {solenoids_front: false, pumps_front: false, solenoids_back: false, pumps_back: false}
            require: []

          p6:
            joints:
              J1: {mode: hold}
              J2: {mode: hold}
              J3: {mode: move_abs, pos:  0.00, vmax: 0.05, amax: 0.20}
              J4: {mode: hold}
              J5: {mode: hold}
              J6: {mode: hold}
              J7: {mode: hold}
            actuators: {solenoids_front: false, pumps_front: false, solenoids_back: false, pumps_back: false}
            require: [J3]

      left:
        meters_per_cycle: 0.05
        between_phase_wait_s: 0.20
        phases:
          p1:
            joints:
              J1: {mode: hold}
              J2: {mode: hold}
              J3: {mode: hold}
              J4: {mode: move_rel, dpos:  0.30, vmax: 1.2, amax: 3.0}
              J5: {mode: move_rel, dpos:  0.30, vmax: 1.2, amax: 3.0}
              J6: {mode: hold}
              J7: {mode: hold}
            actuators: {solenoids_front: true, pumps_front: true, solenoids_back: true, pumps_back: true}
            require: [J4, J5]

          p2:
            joints:
              J1: {mode: hold}
              J2: {mode: hold}
              J3: {mode: hold}
              J4: {mode: move_rel, dpos: -0.30, vmax: 1.2, amax: 3.0}
              J5: {mode: move_rel, dpos: -0.30, vmax: 1.2, amax: 3.0}
              J6: {mode: hold}
              J7: {mode: hold}
            actuators: {solenoids_front: true, pumps_front: true, solenoids_back: true, pumps_back: true}
            require: [J4, J5]

          p3:
            joints:
              J1: {mode: hold}
              J2: {mode: hold}
              J3: {mode: move_abs, pos: -0.05, vmax: 0.05, amax: 0.20}
              J4: {mode: hold}
              J5: {mode: hold}
              J6: {mode: hold}
              J7: {mode: hold}
            actuators: {solenoids_front: true, pumps_front: true, solenoids_back: true, pumps_back: true}
            require: [J3]

          p4:
            joints:
              J1: {mode: hold}
              J2: {mode: hold}
              J3: {mode: hold}
              J4: {mode: move_rel, dpos:  0.30, vmax: 1.2, amax: 3.0}
              J5: {mode: move_rel, dpos:  0.30, vmax: 1.2, amax: 3.0}
              J6: {mode: hold}
              J7: {mode: hold}
            actuators: {solenoids_front: true, pumps_front: true, solenoids_back: true, pumps_back: true}
            require: [J4, J5]

          p5:
            joints:
              J1: {mode: hold}
              J2: {mode: hold}
              J3: {mode: hold}
              J4: {mode: hold}
              J5: {mode: hold}
              J6: {mode: hold}
              J7: {mode: hold}
            actuators: {solenoids_front: false, pumps_front: false, solenoids_back: false, pumps_back: false}
            require: []

          p6:
            joints:
              J1: {mode: hold}
              J2: {mode: hold}
              J3: {mode: move_abs, pos:  0.00, vmax: 0.05, amax: 0.20}
              J4: {mode: hold}
              J5: {mode: hold}
              J6: {mode: hold}
              J7: {mode: hold}
            actuators: {solenoids_front: false, pumps_front: false, solenoids_back: false, pumps_back: false}
            require: [J3]
